### ISSUE TITLE
Translation to german

### ISSUE THREAD

**Issue by tigerxy** [dszymczuk/dsEventCalendar#1]
I've waited for this addon a long time. Great work!
But the addon is only in englisch. Are you interested in translate it in other languages?
I will help you for a german translation.

**Comment by tigerxy** [comment]
I have updated the translation on transifex for german. Please update the languages.

**Comment by dszymczuk** [comment]
When I deploy new version, I will update languages too :)

**Comment by tigerxy** [comment]
Ok great! Thank you :)
