### ISSUE TITLE
Description does not popup in Safari 6

### ISSUE THREAD

**Issue by doctor-zob** [dszymczuk/dsEventCalendar#17]
Great calendar, but the description of an event does not popup in Safari 6.

**Comment by dszymczuk** [comment]
Could you make this step?

 1. Go to Dev Tools (F12)
 2. Go to Console
 3. Clear console
 4. Click on event
 5. Make screen shoot
 6. Send it on eventcalendar@dszymczuk.pl

**Comment by tigerxy** [comment]
I have the same Problem in Google Chrome after Update from 3.0.3 to 3.1.6. The Debugger says:
```
Uncaught TypeError: Cannot read property 'format' of null (index):142 
$.fullCalendar.eventClick dsEventCalendarBlock.js:77
```
and marked this Line:
```
eventClick: function(calEvent, jsEvent, view) {
...
                            end_day += " " + calEvent.end.format(settings.formatEvent);
...
                },
```
In the settings I have a blank field by "Event time format".

What should I insert there?

**Comment by dszymczuk** [comment]
You have to fill with f.e. "HH:mm" - it will display f.e. 13:57 .
Thx for bug find - I will fix it.

**Comment by tigerxy** [comment]
When I insert this and klick the button below, it will be not saved :-(

**Comment by dszymczuk** [comment]
Any error in console ?
I have similar issue while edit event and I try to reproduce it, but it is hard :/

**Comment by tigerxy** [comment]
I think the row in the database is missing.
![bildschirmfoto vom 2015-03-31 10 58 37](https://cloud.githubusercontent.com/assets/7744359/6915523/00778082-d795-11e4-9ba8-412dd04bf876.png)

**Comment by dszymczuk** [comment]
Yep, you don't have: timeFormat

opt: timeFormat
value: hhA:mm

You can add manually, but I will check this for future.

**Comment by tigerxy** [comment]
I can change the field :) but the JavaScript problem with the poupup still exists :(

**Comment by dszymczuk** [comment]
Still problem with this code ? :

```
eventClick: function(calEvent, jsEvent, view) {
...
         end_day += " " + calEvent.end.format(settings.formatEvent);
...
 },
```

**Comment by tigerxy** [comment]
Yes :( Here you can see it live:
http://cvjm-forchheim.de/index.php/veranstaltungen/

**Comment by dszymczuk** [comment]
Could you change time format to: "HH:mm" and check again ?

**Comment by tigerxy** [comment]
Ok changed, but nothing happend. The value in database is ok.

**Comment by dszymczuk** [comment]
Still error ?

It tricky for me. I have only error with end time (I have to refactor my code).

Could you send screen shoot while edit of this event ?

**Comment by tigerxy** [comment]
I can't edit the Event, because the error happens before the popup opens for editing.

I found the problem. When an old event has no "end" value in dsEventCalendarEvents the error happens. You must check if there is a end set.

**Comment by dszymczuk** [comment]
Yes, I found this bug.
I will try to release new version as soon as possible with fixes.

**Comment by tigerxy** [comment]
I have fixt it with this line of SQL:
```
UPDATE `dsEventCalendarEvents` SET `end`=DATE_ADD(`date`, INTERVAL 2 HOUR);
```

**Comment by dszymczuk** [comment]
I have bugs with my code, so I will fix they.

**Comment by dszymczuk** [comment]
Ok, I've uploaded new version. I hope, that it will fixed all bugs.
