### ISSUE TITLE
Error update event

### ISSUE THREAD

**Issue by tigerxy** [dszymczuk/dsEventCalendar#21]
When I want to save and update a Event this error comes in console:

>Failed to load resource: the server responded with a status of 500 (Internal Server Error)
>http://***/dashboard/event_calendar/list_event/updateEvent/

There is no file on my server: controller/dashboard/event_calendar/update_event.php
Version is 3.3.3

**Comment by dszymczuk** [comment]
It is wierd.
You don't need update_event.php file.
This is AJAX request to list_event.php file and call updateEvent function.

I've tested this (C5 version: 5.6.3.1) and everything work. Try clean cache.

If you have still problem - please send me screen with event details.

**Comment by tigerxy** [comment]
Ok I have analysed the POST request an here is the response:
>Ein unerwarteter Fehler ist aufgetreten.
>
>DateTime::__construct() [datetime.--construct]: Failed to parse time string (14 Juni 2015 19:30) at >position 13 (1): Double time specification

**Comment by dszymczuk** [comment]
So, is this bug in DateTime in PHP ?

In next version I will work to better error support.
