### ISSUE TITLE
Update for C5 5.7

### ISSUE THREAD

**Issue by tigerxy** [dszymczuk/dsEventCalendar#9]
Addon is not compatible with Concrete5 5.7.

**Comment by ac0de** [comment]
Any advances on the plugin upgrade? I've been trying to do it but I miss some background in php that could help me through the referencing.

So far I've managed to install it properly, but when the time comes to use the dashboard it's somewhat buggy because it's missing references.

**Comment by dszymczuk** [comment]
At now I'm working on new versions - free and pro. I think that I will release in this or next weekend - I'm testing now.
After that I will create special versions for Concrete 5.7 . Please be patient :)

**Comment by rotech1** [comment]
Also would love to see this on 5.7 ...

**Comment by dszymczuk** [comment]
I'm working on it.
I have to import from 5.6, check if run and adjust new dashboard UI.

**Comment by dszymczuk** [comment]
Here: https://github.com/dszymczuk/dsEventCalendar57
is first working version.

I've uploaded to Concrete5 market, but I have to fix some suggestion from PRB to approve it.

**Comment by tigerxy** [comment]
Very cool!! How can I help you:question: :smiley:

**Comment by dszymczuk** [comment]
These suggestions are easy, so I think that I will finish until end of week.
Here: http://openproject.damianweb.pl/projects/dseventcalendar you can find TASKs to improve for PRB.

When addon will be accept by PRB, I will close this issue with link to market :)

**Comment by dszymczuk** [comment]
I've update to new version (number the same).

**Comment by dszymczuk** [comment]
Approved :)

https://www.concrete5.org/marketplace/addons/ds-event-calendar1/
https://www.concrete5.org/marketplace/addons/ds-event-calendar-pro1/
